### PR TITLE
v1.0.3

### PR DESCRIPTION
**Pull request by Archmonger**
Can we create a new release for versionfield?

Thanks.

### CODE REVIEW

**Comment by Archmonger** [comment]
@carderm

**Comment by carderm** [comment]
done

**Comment by Archmonger** [comment]
@carderm Any chance you can create a version release off this PR?

Last release is from 2020.

**Comment by carderm** [comment]
> @carderm Any chance you can create a version release off this PR?
> 
> Last release is from 2020.
?? 
https://pypi.org/project/django-versionfield/#history

**Comment by carderm** [comment]
done

**Pull request merged**
